//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotovBuilder.AzureFunctions.Properties {
    using System;
    using System.Diagnostics.CodeAnalysis;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [ExcludeFromCodeCoverage]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TotovBuilder.AzureFunctions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while fetching &quot;{0}&quot; blob from Azure Blob storage : {1}.
        /// </summary>
        internal static string BlobFetchingError {
            get {
                return ResourceManager.GetString("BlobFetchingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End : Market data fetching..
        /// </summary>
        internal static string EndMarketDataFetching {
            get {
                return ResourceManager.GetString("EndMarketDataFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End : Static data fetching..
        /// </summary>
        internal static string EndStaticDataFetching {
            get {
                return ResourceManager.GetString("EndStaticDataFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End : Waiting for previous market data fetching to finish..
        /// </summary>
        internal static string EndWaitingPreviousMarketDataFetching {
            get {
                return ResourceManager.GetString("EndWaitingPreviousMarketDataFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End : Waiting for previous static data fetching to finish..
        /// </summary>
        internal static string EndWaitingPreviousStaticDataFetching {
            get {
                return ResourceManager.GetString("EndWaitingPreviousStaticDataFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching delay exceeded..
        /// </summary>
        internal static string FetchingDelayExceeded {
            get {
                return ResourceManager.GetString("FetchingDelayExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;{0}&quot; cache..
        /// </summary>
        internal static string InvalidCache {
            get {
                return ResourceManager.GetString("InvalidCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;{0}&quot; integer configuration value..
        /// </summary>
        internal static string InvalidIntegerConfigurationValue {
            get {
                return ResourceManager.GetString("InvalidIntegerConfigurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid market API response : {0}.
        /// </summary>
        internal static string InvalidMarketApiResponse {
            get {
                return ResourceManager.GetString("InvalidMarketApiResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid market API response data..
        /// </summary>
        internal static string InvalidMarketApiResponseData {
            get {
                return ResourceManager.GetString("InvalidMarketApiResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;{0}&quot; string configuration value..
        /// </summary>
        internal static string InvalidStringConfigurationValue {
            get {
                return ResourceManager.GetString("InvalidStringConfigurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market data fetched from cache..
        /// </summary>
        internal static string MarketDataFetchedFromCache {
            get {
                return ResourceManager.GetString("MarketDataFetchedFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while fetching data from the market API : {0}..
        /// </summary>
        internal static string MarketDataFetchingError {
            get {
                return ResourceManager.GetString("MarketDataFetchingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start : Market data fetching..
        /// </summary>
        internal static string StartMarketDataFetching {
            get {
                return ResourceManager.GetString("StartMarketDataFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start : Static data fetching..
        /// </summary>
        internal static string StartStaticDataFetching {
            get {
                return ResourceManager.GetString("StartStaticDataFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start : Waiting for previous market data fetching to finish..
        /// </summary>
        internal static string StartWaitingPreviousMarketDataFetching {
            get {
                return ResourceManager.GetString("StartWaitingPreviousMarketDataFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start : Waiting for previous static data fetching to finish..
        /// </summary>
        internal static string StartWaitingPreviousStaticDataFetching {
            get {
                return ResourceManager.GetString("StartWaitingPreviousStaticDataFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static data fetched from cache..
        /// </summary>
        internal static string StaticDataFetchedFromCache {
            get {
                return ResourceManager.GetString("StaticDataFetchedFromCache", resourceCulture);
            }
        }
    }
}
