//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotovBuilder.AzureFunctions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TotovBuilder.AzureFunctions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Data fetched from the API..
        /// </summary>
        internal static string ApiDataFetched {
            get {
                return ResourceManager.GetString("ApiDataFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Error while fetching data from the API :
        ///{1}.
        /// </summary>
        internal static string ApiFetchError {
            get {
                return ResourceManager.GetString("ApiFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing Azure Functions configuration :
        ///{0}.
        /// </summary>
        internal static string AzureFunctionsConfigurationDeserializationError {
            get {
                return ResourceManager.GetString("AzureFunctionsConfigurationDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing barter :
        ///{0}.
        /// </summary>
        internal static string BarterDeserializationError {
            get {
                return ResourceManager.GetString("BarterDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing changelog :
        ///{0}.
        /// </summary>
        internal static string ChangelogDeserializationError {
            get {
                return ResourceManager.GetString("ChangelogDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Execution delay exceeded..
        /// </summary>
        internal static string ExecutionDelayExceeded {
            get {
                return ResourceManager.GetString("ExecutionDelayExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Fetching data from the API..
        /// </summary>
        internal static string FetchingApiData {
            get {
                return ResourceManager.GetString("FetchingApiData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating website data..
        /// </summary>
        internal static string GeneratingWebsiteData {
            get {
                return ResourceManager.GetString("GeneratingWebsiteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Invalid API response data :
        ///{1}.
        /// </summary>
        internal static string InvalidApiResponseData {
            get {
                return ResourceManager.GetString("InvalidApiResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration..
        /// </summary>
        internal static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;{0}&quot; string configuration value..
        /// </summary>
        internal static string InvalidStringConfigurationValue {
            get {
                return ResourceManager.GetString("InvalidStringConfigurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing item category :
        ///{0}.
        /// </summary>
        internal static string ItemCategoryDeserializationError {
            get {
                return ResourceManager.GetString("ItemCategoryDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item category &quot;{0}&quot; is not implemented..
        /// </summary>
        internal static string ItemCategoryNotImplemented {
            get {
                return ResourceManager.GetString("ItemCategoryNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing item :
        ///{0}.
        /// </summary>
        internal static string ItemDeserializationError {
            get {
                return ResourceManager.GetString("ItemDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing item missing properties :
        ///{0}.
        /// </summary>
        internal static string ItemMissingPropertiesDeserializationError {
            get {
                return ResourceManager.GetString("ItemMissingPropertiesDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &quot;{0}&quot; not found..
        /// </summary>
        internal static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - No data fetched..
        /// </summary>
        internal static string NoDataFetched {
            get {
                return ResourceManager.GetString("NoDataFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while constructing preset &quot;{0}&quot; :
        ///Cannot find a slot for items &quot;{1}&quot;..
        /// </summary>
        internal static string PresetContructionError {
            get {
                return ResourceManager.GetString("PresetContructionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing preset :
        ///{0}.
        /// </summary>
        internal static string PresetDeserializationError {
            get {
                return ResourceManager.GetString("PresetDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Waiting for previous fetching to finish..
        /// </summary>
        internal static string PreviousFetchingFinished {
            get {
                return ResourceManager.GetString("PreviousFetchingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing price :
        ///{0}.
        /// </summary>
        internal static string PriceDeserializationError {
            get {
                return ResourceManager.GetString("PriceDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing Tarkov values :
        ///{0}.
        /// </summary>
        internal static string TarkovValuesDeserializationError {
            get {
                return ResourceManager.GetString("TarkovValuesDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Waiting for previous fetching to finish..
        /// </summary>
        internal static string WaitingForPreviousFetching {
            get {
                return ResourceManager.GetString("WaitingForPreviousFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing website configuration :
        ///{0}.
        /// </summary>
        internal static string WebsiteConfigurationDeserializationError {
            get {
                return ResourceManager.GetString("WebsiteConfigurationDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website data generated.
        /// </summary>
        internal static string WebsiteDataGenerated {
            get {
                return ResourceManager.GetString("WebsiteDataGenerated", resourceCulture);
            }
        }
    }
}
