//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotovBuilder.AzureFunctions.Properties {
    using System;
    using System.Diagnostics.CodeAnalysis;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [ExcludeFromCodeCoverage]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TotovBuilder.AzureFunctions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing API response to type &quot;{0}&quot; :
        ///{1}.
        /// </summary>
        internal static string ApiResponseDeserializationError {
            get {
                return ResourceManager.GetString("ApiResponseDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing armor penetrations :
        ///{0}.
        /// </summary>
        internal static string ArmorPenetrationsDeserializationError {
            get {
                return ResourceManager.GetString("ArmorPenetrationsDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing Azure Functions configuration :
        ///{0}.
        /// </summary>
        internal static string AzureFunctionsConfigurationDeserializationError {
            get {
                return ResourceManager.GetString("AzureFunctionsConfigurationDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing barter :
        ///{0}.
        /// </summary>
        internal static string BarterDeserializationError {
            get {
                return ResourceManager.GetString("BarterDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while fetching &quot;{0}&quot; blob from Azure Blob storage :
        ///{1}.
        /// </summary>
        internal static string BlobFetchingError {
            get {
                return ResourceManager.GetString("BlobFetchingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing changelog :
        ///{0}.
        /// </summary>
        internal static string ChangelogDeserializationError {
            get {
                return ResourceManager.GetString("ChangelogDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - End : Fetching..
        /// </summary>
        internal static string EndFetching {
            get {
                return ResourceManager.GetString("EndFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - End : Waiting for previous fetching to finish..
        /// </summary>
        internal static string EndWaitingForPreviousFetching {
            get {
                return ResourceManager.GetString("EndWaitingForPreviousFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Fetched from cache..
        /// </summary>
        internal static string FetchedFromCache {
            get {
                return ResourceManager.GetString("FetchedFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Fetching delay exceeded..
        /// </summary>
        internal static string FetchingDelayExceeded {
            get {
                return ResourceManager.GetString("FetchingDelayExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Error while fetching data from the API :
        ///{1}..
        /// </summary>
        internal static string FetchingError {
            get {
                return ResourceManager.GetString("FetchingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Fetching response :
        ///{1}.
        /// </summary>
        internal static string FetchingResponse {
            get {
                return ResourceManager.GetString("FetchingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Fetching response content :
        ///{1}.
        /// </summary>
        internal static string FetchingResponseContent {
            get {
                return ResourceManager.GetString("FetchingResponseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Invalid API query :
        ///{1}.
        /// </summary>
        internal static string InvalidApiQuery {
            get {
                return ResourceManager.GetString("InvalidApiQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Invalid API response data :
        ///{1}.
        /// </summary>
        internal static string InvalidApiResponseData {
            get {
                return ResourceManager.GetString("InvalidApiResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Invalid cache..
        /// </summary>
        internal static string InvalidCache {
            get {
                return ResourceManager.GetString("InvalidCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration..
        /// </summary>
        internal static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;{0}&quot; integer configuration value..
        /// </summary>
        internal static string InvalidIntegerConfigurationValue {
            get {
                return ResourceManager.GetString("InvalidIntegerConfigurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;{0}&quot; string configuration value..
        /// </summary>
        internal static string InvalidStringConfigurationValue {
            get {
                return ResourceManager.GetString("InvalidStringConfigurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing item category :
        ///{0}.
        /// </summary>
        internal static string ItemCategoryDeserializationError {
            get {
                return ResourceManager.GetString("ItemCategoryDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing item :
        ///{0}.
        /// </summary>
        internal static string ItemDeserializationError {
            get {
                return ResourceManager.GetString("ItemDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item category &quot;{0}&quot; is not implemented..
        /// </summary>
        internal static string NotImplementedItemCategory {
            get {
                return ResourceManager.GetString("NotImplementedItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing preset :
        ///{0}.
        /// </summary>
        internal static string PresetDeserializationError {
            get {
                return ResourceManager.GetString("PresetDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing price :
        ///{0}.
        /// </summary>
        internal static string PriceDeserializationError {
            get {
                return ResourceManager.GetString("PriceDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing quest :
        ///{0}.
        /// </summary>
        internal static string QuestDeserializationError {
            get {
                return ResourceManager.GetString("QuestDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Start : Fetching..
        /// </summary>
        internal static string StartFetching {
            get {
                return ResourceManager.GetString("StartFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Start : Waiting for previous fetching to finish..
        /// </summary>
        internal static string StartWaitingForPreviousFetching {
            get {
                return ResourceManager.GetString("StartWaitingForPreviousFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing Tarkov values :
        ///{0}.
        /// </summary>
        internal static string TarkovValuesDeserializationError {
            get {
                return ResourceManager.GetString("TarkovValuesDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing website configuration :
        ///{0}.
        /// </summary>
        internal static string WebsiteConfigurationDeserializationError {
            get {
                return ResourceManager.GetString("WebsiteConfigurationDeserializationError", resourceCulture);
            }
        }
    }
}
